# Generated by Django 5.2.12 on 2026-05-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='compressed_image',
            field=models.ImageField(upload_to='post_app/media/compressed_image/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='original_image',
            field=models.ImageField(upload_to='post_app/media/original_image/'),
        ),
    ]
